config/routes.rb
Permissionwizard::Application.routes.draw do
  resources :admins

  resources :templates do
    collection do
      put :update_multiple
    end
  end

  resources :accounts do
    resources :templates do
      collection do
        put :update_multiple
      end
    end
  end

  post 'accounts/:id/duplicate_templates', :to => 'accounts#duplicate_templates'

  get 'accounts(/:account_id(/:action))' => 'wizard#%{action}'

  root :to => "accounts#new"

end

app/views/templates/_form.html.erb
<h3>
  <%= @account.name %>
</h3>

<%= render :partial => 'shared/new_template_table' %>

<%= link_to "Customize my templates", start_path(:account_id => @account.id) %>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<h1>Listing templates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Home</th>
    <th>Emails</th>
    <th>Bidding</th>
    <th>Prime contract</th>
    <th>Commitments</th>
    <th>Change orders</th>
    <th>Rfis</th>
    <th>Submittals</th>
    <th>Transmittals</th>
    <th>Punch list</th>
    <th>Meetings</th>
    <th>Schedule</th>
    <th>Daily log</th>
    <th>Reports</th>
    <th>Photos</th>
    <th>Drawings</th>
    <th>Documents</th>
    <th>Directory</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @templates.each do |template| %>
  <tr>
    <td><%= template.name %></td>
    <td><%= template.home %></td>
    <td><%= template.emails %></td>
    <td><%= template.bidding %></td>
    <td><%= template.prime_contract %></td>
    <td><%= template.commitments %></td>
    <td><%= template.change_orders %></td>
    <td><%= template.rfis %></td>
    <td><%= template.submittals %></td>
    <td><%= template.transmittals %></td>
    <td><%= template.punch_list %></td>
    <td><%= template.meetings %></td>
    <td><%= template.schedule %></td>
    <td><%= template.daily_log %></td>
    <td><%= template.reports %></td>
    <td><%= template.photos %></td>
    <td><%= template.drawings %></td>
    <td><%= template.documents %></td>
    <td><%= template.directory %></td>
    <td><%= template.admin %></td>
    <td><%= link_to 'Show', template %></td>
    <td><%= link_to 'Edit', edit_template_path(template) %></td>
    <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<div class="row">
  <div class="header span8 offset2">
    <h2>Name your Templates</h2>
  </div>
</div>
<div class="row">
  <div class="header span8 offset2">
    <ul class="unstyled">
      <li>Create one template for each of the different "roles" of people you will have on a project.</li>
      <ul>
        <li>ex: "Project Manager", "Superintendent", "Subcontractor"</li>
      </ul>
      <br>
      <li>If two roles should have very similar permissions, just create one template for both of them</li>
      <ul>
        <li>ex: "Architect/Engineer", "Owner/CM"
        </li>
      </ul>
    </ul>
  </div>
</div>

<div class="row">
  <div class="span4 offset4">
    <%= render :partial => 'shared/new_template_table' %>
    <hr>
    <p>When you're finished...</p>
    <%= link_to "Customize my templates", {:controller => :wizard, :action => :start}, :id => :customize_my_templates, :class => 'btn' %>
  </div>
</div>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @template.name %>
</p>

<p>
  <b>Home:</b>
  <%= @template.home %>
</p>

<p>
  <b>Emails:</b>
  <%= @template.emails %>
</p>

<p>
  <b>Bidding:</b>
  <%= @template.bidding %>
</p>

<p>
  <b>Prime contract:</b>
  <%= @template.prime_contract %>
</p>

<p>
  <b>Commitments:</b>
  <%= @template.commitments %>
</p>

<p>
  <b>Change orders:</b>
  <%= @template.change_orders %>
</p>

<p>
  <b>Rfis:</b>
  <%= @template.rfis %>
</p>

<p>
  <b>Submittals:</b>
  <%= @template.submittals %>
</p>

<p>
  <b>Transmittals:</b>
  <%= @template.transmittals %>
</p>

<p>
  <b>Punch list:</b>
  <%= @template.punch_list %>
</p>

<p>
  <b>Meetings:</b>
  <%= @template.meetings %>
</p>

<p>
  <b>Schedule:</b>
  <%= @template.schedule %>
</p>

<p>
  <b>Daily log:</b>
  <%= @template.daily_log %>
</p>

<p>
  <b>Reports:</b>
  <%= @template.reports %>
</p>

<p>
  <b>Photos:</b>
  <%= @template.photos %>
</p>

<p>
  <b>Drawings:</b>
  <%= @template.drawings %>
</p>

<p>
  <b>Documents:</b>
  <%= @template.documents %>
</p>

<p>
  <b>Directory:</b>
  <%= @template.directory %>
</p>

<p>
  <b>Admin:</b>
  <%= @template.admin %>
</p>


<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>