config/routes.rb
Permissionwizard::Application.routes.draw do
  resources :admins

  resources :templates do
    collection do
      put :update_multiple
    end
  end

  resources :accounts do
    resources :templates do
      collection do
        put :update_multiple
      end
    end
  end

  post 'accounts/:id/duplicate_templates', :to => 'accounts#duplicate_templates'

  get 'accounts(/:account_id(/:action))' => 'wizard#%{action}'

  root :to => "accounts#new"

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :templates
  belongs_to :admin

  validates_presence_of :name, :admin_id

  def self.copy_templates(source_id, destination_id)
    source = Account.includes(:templates).find(source_id)
    source.templates.each do |template|
      template.copy_to(destination_id)
    end
  end





end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])
    @templates = @account.templates
    @defaults = Template.where(is_default: true).order(:id)
    @differences = Template.differences(@templates, @defaults)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
    @templates = @account.templates
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        Account.copy_templates(1, @account.id)
        format.html { redirect_to new_account_template_path(@account), notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        flash[:error] = @account.errors.empty? ? "Error" : @account.errors.full_messages.to_sentence
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        flash[:error] = @account.errors.empty? ? "Error" : @account.errors.full_messages.to_sentence
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  def duplicate_templates
    @account = Account.find(params[:id])
    @new_account = @account.dup
    @new_account.save!
    Account.copy_templates(@account.id, @new_account.id)
    redirect_to edit_account_path(@new_account)
  end

  private

  def account_params
    params.require(:account).permit(:name, :admin_id)
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <div class="row">
    <div class="span4 offset2">
      <%= f.label :name, "What is the name of your company?" %>
    </div>
    <div class="span2">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="span4 offset2">
      <%= f.label :admin_id, "Who is your Account Manager at Procore?" %>
    </div>
    <div class="span2">
      <%= f.collection_select(:admin_id, Admin.all, :id, :full_name, :prompt => 'Select')%>
    </div>
  </div>
  <div class="row">
    <div class="span2 offset8">
      <%= f.submit "Next", :class => "btn" %>
    </div>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<div class="row">
  <div class="span12 centered">
    <h2><%= @account.name %> Permission Templates</h2>
  </div>
</div>
<%= form_tag update_multiple_templates_path, :method => :put do %>
  <% @templates.each do |template| %>
    <h3 class="centered"><%= template.name %></h3>
    <table class="review_table table table-bordered table-condensed">
      <thead>
        <tr>
          <th></th>
          <th>None</th>
          <th>Read Only</th>
          <th>Standard</th>
          <th>Admin</th>
        </tr>
      </thead>
      <tbody>
        <%= fields_for "templates[]", template do |f| %>
          <% all_tabs.each do |tab| %>
            <tr>
              <td><%= f.label tab %></td>
              <td><%= f.radio_button tab, 'None' %></td>
              <td><%= f.radio_button tab, 'Read Only'%></td>
              <td><%= f.radio_button tab, 'Standard'%></td>
              <td><%= f.radio_button tab, 'Admin'%></td>
            </tr>
            <%= hidden_field_tag :account_id, @account.id %>
            <%= hidden_field_tag :tab, params[:action] %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <%= submit_tag "Save and Email", :class => 'btn' %>
<% end %>



<div id="page">
  <div class="logo centered"></div>
</div>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.name %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<div id="splash">
  <div class="row">
    <div id="welcome" class="span12">
    	<h2>Welcome to Procore's Permission Wizard</h2>
    </div>
  </div>
  <div class="row">
    <div id="benefits" class="span8 offset2">
      <ul class="">
        <li>Setting up Permission Templates is probably the most important part of your implementation.</li>
        <li>Getting it done right will save a LOT of time and headaches down the line.</li>
        <li>This interactive wizard will help you understand Procore's permission system and choose appropriate templates for your different project roles.</li>
      </ul>
    </div>
  </div>
  <div id="account_image_holder" class="row">
    <div class="span4 offset4">
      <%= image_tag "https://s3.amazonaws.com/pro-core.com/prostore/7730592_procore_logo_small.gif?AWSAccessKeyId=0PFNH01C4MZVXKXZNK82&Expires=2003432978&Signature=xe%2BaL3JrNRyRFVX0H99gIlyBfwQ%3D" %>
    </div>
  </div>
  <div id="account_form">
    <%= render 'form' %>
  </div>  
</div>

app/views/accounts/show.html.erb
<div class="row">
  <div class="span12 centered">
    <h2><%= @account.name %> Permission Templates</h2>
    <p> Need to change something? <%= link_to "Edit Templates", {:controller => :accounts, :action => :duplicate_templates}, :method => :post %> </p>
  </div>
</div>
<% @templates.each do |template| %>
  <div class="header row">
    <div class="span12 centered">
      <h3><%= template.name %></h3>
    </div>
  </div>
  <table id="<%= template.name %>" class="review_table table table-bordered table-condensed">
    <tr>
      <th>Tab</th>
      <th>None</th>
      <th>Read Only</th>
      <th>Standard</th>
      <th>Admin</th>
    </tr>
  <%= form_for template do |f| %>
	  <% all_tabs.each do |tab| %>
      <% if @differences[template.name] and @differences[template.name].include? tab %>
        <tr class="different_row">
      <% else %>
        <tr>
      <% end %>
        <td>
          <%= f.label tab %>
        </td>
        <td>
          <%= f.radio_button tab, 'None', :disabled => true %>
        </td>
        <td>
          <%= f.radio_button tab, 'Read Only', :disabled => true%>
        </td>
        <td>
          <%= f.radio_button tab, 'Standard', :disabled => true%>
        </td>
        <td>
          <%= f.radio_button tab, 'Admin', :disabled => true%>
        </td>
      </tr>
    <% end %>
  <% end %>
  </table>
<% end %>